Add test cases with Rspec
flpfar/tic-tac-toe pull request #6
Opened 2020-04-07 15:48 UTC by flpfar

This branch adds tests for Board, BoarChecker and BoardFormatter classes.
In Board, it tests:
- If it initializes the board correctly with two players
- If it validates the moves and inserts them into the board

In BoardChecker:
- Try all the test cases for diagonal, horizontal and vertical to check if there is a winner.
- Returns false if there is no winner.

In BoardFormatter, it checks:
- If the string returned is formatted as expected.

2020-04-07 19:49 UTC, mosesogwo requested changes
**Hi @flpfar, @FrancoRosa :clap:. Good work on your tests. Just a few required changes :fast_forward:**
 - You should have one **it** block for each expected behaviour. See comments on your code.
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png)

- Add instruction on how to run tests to your README.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-07 19:49 UTC, mosesogwo commented on spec/board_spec.rb
> +      expect(board.players).to eq(0 => 'Player1', 1 => 'Player2')
Split this into two _**it**_ blocks

2020-04-07 19:49 UTC, mosesogwo commented on spec/boardchecker_spec.rb
> +    expect(BoardChecker.winner?(case789)).to be true
Split this and other such similar setups into separate _**it**_ blocks - one for each expectation.

2020-04-07 19:49 UTC, mosesogwo commented on spec/boardchecker_spec.rb
> +    expect(BoardChecker.winner?(case369)).to be true
See previous comments about it blocks.

2020-04-07 19:49 UTC, mosesogwo commented on spec/boardchecker_spec.rb
> +    expect(BoardChecker.winner?(case357)).to eq(true)
See previous comments about it blocks.

2020-04-07 21:06 UTC, flpfar commented
Thank you for reviewing our code, @mosesogwo! The changes in the code were implemented :+1:
About the README, we already have those instructions. Should it be even more descriptive?

2020-04-07 22:33 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @flpfar and @FrancoRosa :handshake: 

### Thank you for doing the changes requested by the previous reviewer, I think your test cases meet the standards and there's only one more thing to work on before moving on:

#### Project Specific

* [x] specs cover positive and negative scenarios ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

- I see all your test cases are positive so please add some negative ones using the not_to method and having negative It blocks

Example:

this positive test case could be changed to be a negative test case like this:

```ruby
#Positive
    it 'returns false when the position of the board is already filled' do
      board.register_move(0, 1)
      expect(board.register_move(1, 1)).to be false
    end

#Negative
    it "doesn't return true if the position of the board is already filled" do
      board.register_move(0, 1)
      expect(board.register_move(1, 1)).not_to be true
    end
```

### That's it, Team! :raised_hands: 

### Please :pray: do the changes :man_technologist: :man_technologist: and submit for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-04-08 00:02 UTC, flpfar commented
Thank you for reviewing our code, @euqueme ! The requested changes have already been implemented. :+1:

2020-04-08 01:12 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @flpfar and @FrancoRosa :handshake: 

### Thank you for doing the changes, amazing work you may move on! :tada: :tada: :tada: 

PROJECT STATUS: APPROVED :heavy_check_mark:

2020-04-08 02:02 UTC, merged